# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v6
    - run: npm ci
      working-directory: ./hello-world/
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0
      with:
        artifact-name: sbom.json
        format: cyclonedx-json
        path: ./hello-world/
        output-file: /tmp/sbom.json 
    - uses: DependencyTrack/gh-upload-sbom@v3
      with:
        serverhostname: 'depapi.zrmt.com'
        apikey: ${{ secrets.DEPENDENCY_API_KEY }}
        projectname: 'Demo SAM App'
        projectversion: 'main'
        bomfilename: "./hello-world/sbom.json"
        autocreate: true
